### ISSUE TITLE
0.10 release

### ISSUE THREAD

**Issue by amousset** [lettre/lettre.rs#4]
* [x] rc1 post
* [x] updated code example
* [x] final release post

**Comment by amousset** [comment]
Made a first pass on the announcement in https://github.com/lettre/lettre.rs/commit/59388f833ddbc32025293f51ad7d87d2b3efb17f

**Comment by amousset** [comment]
@paolobarbolini I updated the 0.10 draft and published it as rc1 announcement on https://lettre.rs/post/lettre-0-10-0-rc-1/.

I'll let you read and check it (and improve it if you want!) and then if you're ok we can publish it on reddit/etc.

**Comment by paolobarbolini** [comment]
Should we share this now on Reddit so that we get views both from the EU and from the US?

**Comment by amousset** [comment]
Posted https://www.reddit.com/r/rust/comments/nhncge/lettre_0100rc1_build_and_send_emails_in_rust/
